# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kara/bazaar_projects/inspect_hw_logs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kara/bazaar_projects/inspect_hw_logs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kara/bazaar_projects/inspect_hw_logs/CMakeFiles /home/kara/bazaar_projects/inspect_hw_logs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kara/bazaar_projects/inspect_hw_logs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyStaticLib

# Build rule for target.
MyStaticLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyStaticLib
.PHONY : MyStaticLib

# fast build rule for target.
MyStaticLib/fast:
	$(MAKE) -f CMakeFiles/MyStaticLib.dir/build.make CMakeFiles/MyStaticLib.dir/build
.PHONY : MyStaticLib/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

app/main.o: app/main.cc.o

.PHONY : app/main.o

# target to build an object file
app/main.cc.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/app/main.cc.o
.PHONY : app/main.cc.o

app/main.i: app/main.cc.i

.PHONY : app/main.i

# target to preprocess a source file
app/main.cc.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/app/main.cc.i
.PHONY : app/main.cc.i

app/main.s: app/main.cc.s

.PHONY : app/main.s

# target to generate assembly for a file
app/main.cc.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/app/main.cc.s
.PHONY : app/main.cc.s

src/mbo_update_raw_t.o: src/mbo_update_raw_t.cc.o

.PHONY : src/mbo_update_raw_t.o

# target to build an object file
src/mbo_update_raw_t.cc.o:
	$(MAKE) -f CMakeFiles/MyStaticLib.dir/build.make CMakeFiles/MyStaticLib.dir/src/mbo_update_raw_t.cc.o
.PHONY : src/mbo_update_raw_t.cc.o

src/mbo_update_raw_t.i: src/mbo_update_raw_t.cc.i

.PHONY : src/mbo_update_raw_t.i

# target to preprocess a source file
src/mbo_update_raw_t.cc.i:
	$(MAKE) -f CMakeFiles/MyStaticLib.dir/build.make CMakeFiles/MyStaticLib.dir/src/mbo_update_raw_t.cc.i
.PHONY : src/mbo_update_raw_t.cc.i

src/mbo_update_raw_t.s: src/mbo_update_raw_t.cc.s

.PHONY : src/mbo_update_raw_t.s

# target to generate assembly for a file
src/mbo_update_raw_t.cc.s:
	$(MAKE) -f CMakeFiles/MyStaticLib.dir/build.make CMakeFiles/MyStaticLib.dir/src/mbo_update_raw_t.cc.s
.PHONY : src/mbo_update_raw_t.cc.s

src/mbp_update_t.o: src/mbp_update_t.cc.o

.PHONY : src/mbp_update_t.o

# target to build an object file
src/mbp_update_t.cc.o:
	$(MAKE) -f CMakeFiles/MyStaticLib.dir/build.make CMakeFiles/MyStaticLib.dir/src/mbp_update_t.cc.o
.PHONY : src/mbp_update_t.cc.o

src/mbp_update_t.i: src/mbp_update_t.cc.i

.PHONY : src/mbp_update_t.i

# target to preprocess a source file
src/mbp_update_t.cc.i:
	$(MAKE) -f CMakeFiles/MyStaticLib.dir/build.make CMakeFiles/MyStaticLib.dir/src/mbp_update_t.cc.i
.PHONY : src/mbp_update_t.cc.i

src/mbp_update_t.s: src/mbp_update_t.cc.s

.PHONY : src/mbp_update_t.s

# target to generate assembly for a file
src/mbp_update_t.cc.s:
	$(MAKE) -f CMakeFiles/MyStaticLib.dir/build.make CMakeFiles/MyStaticLib.dir/src/mbp_update_t.cc.s
.PHONY : src/mbp_update_t.cc.s

src/md_test_t.o: src/md_test_t.cc.o

.PHONY : src/md_test_t.o

# target to build an object file
src/md_test_t.cc.o:
	$(MAKE) -f CMakeFiles/MyStaticLib.dir/build.make CMakeFiles/MyStaticLib.dir/src/md_test_t.cc.o
.PHONY : src/md_test_t.cc.o

src/md_test_t.i: src/md_test_t.cc.i

.PHONY : src/md_test_t.i

# target to preprocess a source file
src/md_test_t.cc.i:
	$(MAKE) -f CMakeFiles/MyStaticLib.dir/build.make CMakeFiles/MyStaticLib.dir/src/md_test_t.cc.i
.PHONY : src/md_test_t.cc.i

src/md_test_t.s: src/md_test_t.cc.s

.PHONY : src/md_test_t.s

# target to generate assembly for a file
src/md_test_t.cc.s:
	$(MAKE) -f CMakeFiles/MyStaticLib.dir/build.make CMakeFiles/MyStaticLib.dir/src/md_test_t.cc.s
.PHONY : src/md_test_t.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... MyStaticLib"
	@echo "... run"
	@echo "... app/main.o"
	@echo "... app/main.i"
	@echo "... app/main.s"
	@echo "... src/mbo_update_raw_t.o"
	@echo "... src/mbo_update_raw_t.i"
	@echo "... src/mbo_update_raw_t.s"
	@echo "... src/mbp_update_t.o"
	@echo "... src/mbp_update_t.i"
	@echo "... src/mbp_update_t.s"
	@echo "... src/md_test_t.o"
	@echo "... src/md_test_t.i"
	@echo "... src/md_test_t.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

